export default {
    FETCH_RANDOM_MOVIE: 'FETCH_RANDOM_MOVIE',
    FETCH_BEST_MOVIES: 'FETCH_BEST_MOVIES',
    FETCH_MOVIES_BY_GENRE: 'FETCH_MOVIES_BY_GENRE',
    FETCH_BY_CRITERIA: 'FETCH_BY_CRITERIA'
};